# Generated by Django 5.2.15 on 2026-06-21 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
